# Site settings
title: Bai BioAI‑Comp Lab
email: baiju@ucmail.uc.edu
description: Academic webpage of Dr. Jun Bai research lab.
baseurl: ""
url: ""
affiliation: University of Cincinnati
# Google analytics ID
google_analytics: 

# Location info. (shown in footer)
location: >
  Coordinates: <br/>
  Department of Computer Science <br/>
  University of Cincinnati <br/>
  Digital Future<br/>
  Cincinnati, OH 45221<br/>

# Contact info. (shown in footer)
contact: >
    Contact Jun via email: <a href="mailto:baiju@ucmail.uc.edu" target="_blank">baiju@ucmail.uc.edu</a> <br/>
    <br/><a href="/aboutwebsite.html">Use this webpage as a template for your own!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: Teams
  - name: Publication
  - name: research
  - name: Teaching
# - name: team
# - name: teaching

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
